### ISSUE TITLE
NameError: name 'Panel' is not defined

### ISSUE THREAD

**Issue by AwesomeRck3** [man-group/arctic#904]
#### Arctic Version

```
arctic                    1.80.0 
```

#### Arctic Store

```
Version Store
```

#### Platform and version

Python 3.8
Pandas 1.2.1

#### Description of problem and/or code sample that reproduces the issue

Hi All,

Looking for some guidance here. Was using Arctic Version Store to store dataframes. Recently updated my system and now getting errors when I try to write to library.

First message is: "Pandas dataframe <df> contains Objects, saving as Blob"

with the final error message being: "NameError: name 'Panel' is not defined"

**Comment by dbrakenhoff** [comment]
There are quite some posts on this issue See #903  or #887 or #884 . The easiest solution for now is to downgrade pandas to e.g. 1.0.3 until the PRs that address this issue are accepted.

As for your first message, I think that happens when the dtype of a column or dataframe is object, in which case the data is stored as a blob (which is much slower).

**Comment by AwesomeRck3** [comment]
Apologies, I see now. Resolved by reverting to 1.0.3. Many thanks.
